import Foundation
import XCTest
@testable import Wand

final class TaskBoardTests: XCTestCase {
    func testBoardTaskDecodesWorkspaceTaskBindingAndTerminalLabels() throws {
        // 看板卡片靠 workspaceTaskId 才能带着任务上下文打开会话。
        let bound = try JSONDecoder().decode(
            WandBoardTask.self,
            from: Data(
                #"{"id":"t-1","title":"修顶栏","status":"doing","workspaceTaskId":"wt-1","sessions":[]}"#.utf8
            )
        )
        XCTAssertEqual(bound.workspaceTaskId, "wt-1")

        // 旧服务端不返回该字段，或者返回空串：都当“未绑定”。
        let unbound = try JSONDecoder().decode(
            WandBoardTask.self,
            from: Data(#"{"id":"t-2","title":"无归属","status":"todo","workspaceTaskId":""}"#.utf8)
        )
        XCTAssertNil(unbound.workspaceTaskId)
        let missing = try JSONDecoder().decode(
            WandBoardTask.self,
            from: Data(#"{"id":"t-3","title":"旧数据","status":"todo"}"#.utf8)
        )
        XCTAssertNil(missing.workspaceTaskId)

        // 空白终端的 provider 是 shell/session，不能把内部标识当工具名印在卡片上。
        XCTAssertEqual(wandBoardProviderLabel("shell"), "终端")
        XCTAssertEqual(wandBoardProviderLabel("session"), "终端")
        XCTAssertEqual(wandBoardProviderLabel("pi"), "Pi")
        XCTAssertEqual(wandBoardProviderLabel(""), "Agent")
    }

    func testBoardTaskDecoderReadsWorkspaceAgentAndSessions() throws {
        let json = """
        {
          "id": "task-1",
          "workspaceId": "ws-1",
          "identifier": "TASK-1",
          "title": "修顶栏",
          "description": "对齐 iOS",
          "status": "doing",
          "priority": "high",
          "labels": ["ui"],
          "sortOrder": 2,
          "agent": { "provider": "codex", "model": "default", "thinkingEffort": "deep" },
          "sessionIds": ["sess-1"],
          "sessions": [{
            "id": "sess-1",
            "provider": "codex",
            "sessionKind": "structured",
            "title": "修顶栏",
            "status": "running",
            "cwd": "/repo",
            "model": "gpt-5",
            "thinkingEffort": "deep"
          }],
          "workspace": { "id": "ws-1", "name": "wand", "cwd": "/repo" }
        }
        """.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertEqual(task.id, "task-1")
        XCTAssertEqual(task.workspaceId, "ws-1")
        XCTAssertEqual(task.status, "doing")
        XCTAssertEqual(task.agent?.provider, "codex")
        // 服务端未返回 mode：按 provider 支持范围夹取（codex 只有 full-access）。
        XCTAssertEqual(task.agent?.mode, "full-access")
        XCTAssertEqual(task.workspace?.name, "wand")
        XCTAssertEqual(task.sessions.first?.id, "sess-1")
        XCTAssertTrue(task.sessions.first?.isStructured == true)
    }

    func testBoardTaskDecoderAllowsUnassignedProjectAndAgent() throws {
        let json = #"{"id":"task-2","title":"草稿"}"#.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertNil(task.workspaceId)
        XCTAssertNil(task.agent)
        XCTAssertEqual(task.status, "todo")
        XCTAssertEqual(task.priority, "none")
        XCTAssertTrue(task.sessions.isEmpty)
        // 老服务端不返回 titleSource，按用户手写处理。
        XCTAssertEqual(task.titleSource, "user")
    }

    func testBoardTaskDecoderReadsAutoGeneratedTitleSource() throws {
        let json = #"{"id":"task-3","title":"根据描述生成的标题","titleSource":"auto"}"#.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertEqual(task.titleSource, "auto")
    }

    func testAgentModeDefaultsAndClamps() {
        XCTAssertEqual(wandBoardNormalizedMode(provider: "codex", mode: "managed"), "full-access")
        XCTAssertEqual(wandBoardNormalizedMode(provider: "claude", mode: "bogus"), "default")
        XCTAssertEqual(wandBoardSupportedModes("codex"), ["full-access"])
        XCTAssertEqual(wandBoardModeLabel("managed"), "托管")
        XCTAssertEqual(wandBoardModeLabel("full-access"), "全权限")
        XCTAssertEqual(wandBoardModeLabel("default"), "标准")
        let agent = WandBoardTaskAgent(provider: "claude", model: "default", thinkingEffort: "off", mode: "managed")
        XCTAssertEqual(agent.jsonObject()["mode"] as? String, "managed")
        XCTAssertEqual(agent.mode, "managed")
    }

    func testBoardLabelsCoverColumns() {
        XCTAssertEqual(WandBoardStatus.todo.label, "待办")
        XCTAssertEqual(WandBoardStatus.doing.label, "进行中")
        XCTAssertEqual(WandBoardStatus.done.label, "已完成")
        XCTAssertEqual(WandBoardPriority.urgent.label, "紧急")
        XCTAssertEqual(wandBoardProviderLabel("pi"), "Pi")
        XCTAssertEqual(wandBoardEffortLabel("deep"), "深入")
    }


    func testSessionsGroupByTheAgentsThatRan() {
        let json = """
        {
          "id": "task-9",
          "title": "多 Agent",
          "agent": { "provider": "claude", "model": "opus", "thinkingEffort": "deep" },
          "sessions": [
            { "id": "s1", "provider": "claude", "title": "修登录", "status": "running", "model": "opus", "thinkingEffort": "deep" },
            { "id": "s2", "provider": "claude", "title": "补测试", "status": "exited", "model": "sonnet", "thinkingEffort": "off" },
            { "id": "s3", "provider": "codex", "title": "实现 API", "status": "idle", "model": "gpt-5", "thinkingEffort": "standard" }
          ]
        }
        """.data(using: .utf8)!
        let task = try! JSONDecoder().decode(WandBoardTask.self, from: json)
        let groups = wandBoardSessionGroups(sessions: task.sessions, assigned: task.agent)
        XCTAssertEqual(groups.map(\.provider), ["claude", "codex"])
        XCTAssertEqual(groups[0].sessions.map(\.id), ["s1", "s2"])
        XCTAssertEqual(groups[1].sessions.map(\.id), ["s3"])
        let pending = wandBoardSessionGroups(
            sessions: [],
            assigned: WandBoardTaskAgent(provider: "pi", model: "default", thinkingEffort: "off")
        )
        XCTAssertEqual(pending.count, 1)
        XCTAssertEqual(pending.first?.provider, "pi")
        XCTAssertTrue(pending.first?.sessions.isEmpty == true)
    }

    func testSwipeActionsFollowAndroidStatusContract() {
        XCTAssertEqual(wandBoardSwipeAction(for: "todo"), .start)
        XCTAssertEqual(wandBoardSwipeAction(for: "doing"), .complete)
        XCTAssertEqual(wandBoardSwipeAction(for: "done"), .archive)
        XCTAssertNil(wandBoardSwipeAction(for: "archived"))
        XCTAssertEqual(wandBoardSwipeTargetStatus(.start), "doing")
        XCTAssertEqual(wandBoardSwipeTargetStatus(.complete), "done")
        XCTAssertNil(wandBoardSwipeTargetStatus(.archive))
        XCTAssertEqual(wandBoardSwipeActionTitle(.start), "开始任务？")
        XCTAssertEqual(wandBoardToggledStatus("doing"), "done")
        XCTAssertEqual(wandBoardToggledStatus("done"), "todo")
    }

    func testProcessingAndAgentRunningLabels() throws {
        let json = """
        {
          "id": "task-run",
          "title": "",
          "description": "项目：wand\\n修登录",
          "status": "doing",
          "sessions": [{ "id": "s1", "provider": "claude", "status": "running" }]
        }
        """.data(using: .utf8)!
        let task = try JSONDecoder().decode(WandBoardTask.self, from: json)
        XCTAssertEqual(wandBoardCardTitle(task), "修登录")
        XCTAssertEqual(wandBoardProcessingLabel(task), "正在处理...")
        XCTAssertTrue(wandBoardAgentRunning(task))
        XCTAssertEqual(wandBoardAgentLabels(sessions: task.sessions, assigned: task.agent), "Claude")
    }

    func testBoardTaskStatsCountRemainingAndPriority() throws {
        let json = """
        [
          {"id":"a","status":"todo","priority":"urgent"},
          {"id":"b","status":"doing","priority":"none"},
          {"id":"c","status":"done","priority":"high"},
          {"id":"d","status":"archived","priority":"low"}
        ]
        """.data(using: .utf8)!
        let tasks = try JSONDecoder().decode([WandBoardTask].self, from: json)
        let stats = wandBoardTaskStats(tasks)
        XCTAssertEqual(stats.total, 4)
        XCTAssertEqual(stats.todo, 1)
        XCTAssertEqual(stats.doing, 1)
        XCTAssertEqual(stats.done, 1)
        XCTAssertEqual(stats.remaining, 2)
        XCTAssertEqual(stats.high, 2)
    }

}
